language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
matrix:
  allow_failures:
    - jdk: openjdk11
    - jdk: openjdk-ea
  fast_finish: true
install: true
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
script:
  - mvn test -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
jobs:
  include:
    - stage: deploy
      if: branch =~ /^(?:master|\d+\.\d+(\.\d+)?(-\S*)?)$/ AND type != pull_request AND fork = false
      script: skip
      jdk: openjdk8
      deploy:
        -
          provider: script
          script: .travis/deploy.sh
          skip_cleanup: true
          on:
            repo: rapid7/docker-image-analyzer
            branch: master
        -
          provider: script
          script: .travis/deploy.sh
          skip_cleanup: true
          on:
            repo: rapid7/docker-image-analyzer
            tags: true
cache:
  directories:
    - $HOME/.m2
